#!/bin/bash

# Đặt giá trị IPV6ADDR từ tham số đầu vào
if [ -z "$1" ]; then
    echo "Vui lòng cung cấp địa chỉ IPv6 làm tham số đầu vào."
    exit 1
fi

cat << 'EOF' | sudo tee /etc/motd
####################################################################
#        _           _   _   _                                     #
#       | |         (_) | \ | |                                    #
#       | |     ___  _  |  \| | __ _ _   _ _   _  ___ _ __         #
#       | |    / _ \| | | . ` |/ _` | | | | | | |/ _ \ '_ \        #
#       | |___| (_) | | | |\  | (_| | |_| | |_| |  __/ | | |       #
#       |______\___/|_| |_| \_|\__, |\__,_|\__, |\___|_| |_|       #
#                               __/ |       __/ |                  #
#                              |___/       |___/                   #
####################################################################
#                                                                  #
# Website: https://lowji194.github.io/                             #
# Nếu mua tool RegProxy không giới hạn số lượng thì inbox cho mình #
# Nguyễn Thế Lợi                                                   #
# SĐT: 0963 159 294                                                #
# Facebook: https://www.facebook.com/Lowji194/                     #
#                                                                  #
####################################################################
EOF

IPV6ADDR="$1"
IPV6_DEFAULTGW=$(echo "$IPV6ADDR" | sed 's/::[a-fA-F0-9]*/::1/')

# Lấy tên interface mạng
Eth=$(ip addr show | grep -E '^2:' | sed 's/^[0-9]*: \(.*\):.*/\1/')

# Thêm /64 nếu chưa có
if [[ ! "$IPV6ADDR" =~ /64$ ]]; then
    IPV6ADDR="${IPV6ADDR}/64"
fi

CONFIG_FILE="/etc/sysconfig/network-scripts/ifcfg-${Eth}"

# Cập nhật hoặc thêm cấu hình vào tệp
if grep -q "Write=true" "$CONFIG_FILE"; then
    # Thay thế các dòng IPV6ADDR và IPV6_DEFAULTGW với giá trị mới
    sed -i "s|^IPV6ADDR=.*|IPV6ADDR=$IPV6ADDR|" "$CONFIG_FILE"
    sed -i "s|^IPV6_DEFAULTGW=.*|IPV6_DEFAULTGW=$IPV6_DEFAULTGW|" "$CONFIG_FILE"
else
    echo "Write=true
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6ADDR=$IPV6ADDR
IPV6_DEFAULTGW=$IPV6_DEFAULTGW" >> "$CONFIG_FILE"
fi

# Khởi động lại dịch vụ mạng
if [ -f /etc/almalinux-release ]; then
    sudo systemctl restart NetworkManager
else
    service network restart
fi
sleep 3

# Kiểm tra kết nối mạng IPv6
ping6 google.com -c4

IP=$(curl -6 -s icanhazip.com)
if [ -n "$IP" ]; then
    echo "Bật IPv6 thành công: $IP" 
else
    echo "Thất bại kiểm tra lại IP, VPS hoặc liên hệ Cloudfly" 
fi

